# Generated by Django 5.1 on 2024-09-14 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('roomTypeID', models.AutoField(primary_key=True, serialize=False)),
                ('room_type_name', models.CharField(max_length=50)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('max_occupancy', models.IntegerField()),
                ('room_description', models.CharField(max_length=500)),
            ],
        ),
    ]
