# Generated by Django 5.1 on 2024-09-08 04:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_alter_customuser_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_login',
            field=models.DateTimeField(db_column='LastLogin', default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='session',
            name='userID',
            field=models.ForeignKey(db_column='UserID', on_delete=django.db.models.deletion.CASCADE, to='Accounts.customuser'),
        ),
    ]
