# Generated by Django 5.1 on 2024-09-14 02:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Rooms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('reservationID', models.AutoField(primary_key=True, serialize=False)),
                ('number_of_guests', models.SmallIntegerField()),
                ('check_in_date', models.DateField()),
                ('check_out_date', models.DateField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reservation_status', models.CharField(default='Confirmed', max_length=9)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Rooms.room')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
