# Generated by Django 5.1 on 2024-09-14 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reservations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='reservation_status',
            field=models.CharField(default='Confirmed', max_length=20),
        ),
    ]
