# Generated by Django 5.1 on 2024-09-08 04:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_customuser_last_login_alter_session_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='last_login',
            field=models.DateTimeField(db_column='lastLogin', default=django.utils.timezone.now),
        ),
    ]
