# Generated by Django 5.1 on 2024-09-14 02:36

import django.contrib.auth.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0006_remove_customuser_date_joined_and_more'),
    ]

    operations = [
    ]
