# Generated by Django 5.1 on 2024-09-14 04:14

import django.contrib.auth.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0007_customuser_date_joined_customuser_is_active_and_more'),
    ]

    operations = [
        
        migrations.DeleteModel(
            name='Session',
        ),
    ]
