# Generated by Django 5.1 on 2024-09-08 05:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0004_alter_customuser_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(db_column='DateJoined', default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(db_column='IsActive', default=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_staff',
            field=models.BooleanField(db_column='IsStaff', default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_superuser',
            field=models.BooleanField(db_column='IsSuperUser', default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='password',
            field=models.CharField(blank=True, db_column='Password', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='username',
            field=models.CharField(db_column='Username', default='default', max_length=150),
        ),
    ]
