# Generated by Django 5.1 on 2024-09-24 22:07

import django.contrib.auth.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0008_customuser_date_joined_customuser_is_active_and_more'),
    ]

    operations = [
    ]
